// Code generated by protoc-gen-go.
// source: github.com/libreoscar/crypto/crypto.proto
// DO NOT EDIT!

/*
Package crypto is a generated protocol buffer package.

It is generated from these files:
	github.com/libreoscar/crypto/crypto.proto

It has these top-level messages:
	PublicKey256
	KeyPair256
	Signature256
	Digest256
	Digests256
*/
package crypto

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// DO NOT modify its field directly, object of this class is treated as immutable
type PublicKey256 struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PublicKey256) Reset()         { *m = PublicKey256{} }
func (m *PublicKey256) String() string { return proto.CompactTextString(m) }
func (*PublicKey256) ProtoMessage()    {}

// DO NOT modify its field directly, object of this class is treated as immutable
type KeyPair256 struct {
	PrivKey   []byte        `protobuf:"bytes,1,opt,name=priv_key,proto3" json:"priv_key,omitempty"`
	PublicKey *PublicKey256 `protobuf:"bytes,2,opt,name=public_key" json:"public_key,omitempty"`
}

func (m *KeyPair256) Reset()         { *m = KeyPair256{} }
func (m *KeyPair256) String() string { return proto.CompactTextString(m) }
func (*KeyPair256) ProtoMessage()    {}

func (m *KeyPair256) GetPublicKey() *PublicKey256 {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

// DO NOT modify its field directly, object of this class is treated as immutable
type Signature256 struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Signature256) Reset()         { *m = Signature256{} }
func (m *Signature256) String() string { return proto.CompactTextString(m) }
func (*Signature256) ProtoMessage()    {}

// DO NOT modify its field directly, object of this class is treated as immutable
type Digest256 struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Digest256) Reset()         { *m = Digest256{} }
func (m *Digest256) String() string { return proto.CompactTextString(m) }
func (*Digest256) ProtoMessage()    {}

type Digests256 struct {
	Digests []*Digest256 `protobuf:"bytes,1,rep,name=digests" json:"digests,omitempty"`
}

func (m *Digests256) Reset()         { *m = Digests256{} }
func (m *Digests256) String() string { return proto.CompactTextString(m) }
func (*Digests256) ProtoMessage()    {}

func (m *Digests256) GetDigests() []*Digest256 {
	if m != nil {
		return m.Digests
	}
	return nil
}
